WITH SOURCE_DATA AS (
    SELECT *
    FROM {{ source('abc_bank', 'ABC_BANK_POSITION') }}
),

PROFIT AS (
    SELECT
        *,
        POSITION_VALUE - COST_BASE as UNREALIZED_PROFIT,
        ROUND(UNREALIZED_PROFIT / COST_BASE, 5) as UNREALIZED_PROFIT_PCT
    FROM SOURCE_DATA
)

SELECT * FROM PROFIT